name: FINSIGHT CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build Docker images
        run: |
          docker compose build

      - name: Start services
        run: |
          docker compose up -d
          sleep 30  # Give services time to start

      - name: Ingest data and assert endpoints
        run: |
          # Ingest data for AAPL with retries
          for i in {1..3}; do curl -f http://localhost:8000/ingest/AAPL && break || sleep 5; done || exit 1
          # Analyze AAPL with retries
          for i in {1..3}; do curl -f http://localhost:8001/analyze/AAPL && break || sleep 5; done || exit 1
          # Assert frontend endpoint returns 200 OK
          for i in {1..3}; do curl -f -o /dev/null -s -w "%{http_code}" http://localhost:5173 | grep -q 200 && break || sleep 5; done || { echo "Frontend endpoint failed"; exit 1; }
          # Add more endpoint assertions if needed
          echo "All endpoints asserted successfully"

  cleanup:
    runs-on: self-hosted
    needs: test
    if: always()  # Runs even if test job fails
    steps:
      - name: Stop services
        run: |
          docker compose down